ci: split Dockerfiles & CI update
Refs: #24

Signed-off-by: Jakub Vokoun <jakub.vokoun@gmail.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,51 +1,165 @@
 
 stages:
   - test
-  - build
+  - build_base
+  - build_app
   - deploy
 
 variables:
   CACHE_REGISTRY: docker.app.knihovny.cz
   TARGET_REGISTRY: registry.app.knihovny.cz
-  BUILD_IMAGE: "docker.app.knihovny.cz/ci-builds/buildah"
+  BUILD_JOB_IMAGE: "docker.app.knihovny.cz/ci-builds/buildah"
+  PHP_IMAGE_NAME: moravianlibrary/registrace/php
+  IMAGE_NAME: moravianlibrary/registrace/app
+  DEPLOY_JOB_IMAGE: "docker.app.knihovny.cz/ci-builds/kustomize:latest"
   BUILDAH_LAYERS: 'true'
-  IMAGE_NAME: moravianlibrary/registrace
 
 Test the code:
   stage: test
+  only:
+    refs:
+      - master
+      - /^devel/
+      - merge_requests
   script:
     - echo "OK"
 
-Build container:
-  stage: build
-  image: "${BUILD_IMAGE}"
-  variables:
-    IMAGE_CACHE_FILE: "${CI_PROJECT_DIR}/.cache/${CI_PROJECT_PATH_SLUG}.tar"
-  cache:
-    key: '${CI_PROJECT_NAME}'
-    paths:
-      - .cache
-    policy: pull-push
+Build PHP image:
+  stage: build_base
+  image: "${BUILD_JOB_IMAGE}"
+  only:
+    refs:
+      - master
+      - /^devel/
+      - merge_requests
+    changes:
+      - build/php-image/*
+      - build/php-image/**/*
+
   before_script:
-    - mkdir -p .cache
-    # try to load image from previous builds
-    #- if [ -f "${IMAGE_CACHE_FILE}" ]; then buildah pull --quiet docker-archive:${IMAGE_CACHE_FILE} ;  fi
     # try to load image from cache registry
-    - if buildah pull --quiet docker://${CACHE_REGISTRY}/${IMAGE_NAME}:latest ; then echo Cache loaded 1>&2 ; fi
-    - if buildah pull --quiet docker://${CACHE_REGISTRY}/${IMAGE_NAME}:build ; then echo Cache loaded 1>&2 ; fi
+    - if buildah pull --quiet docker://${CACHE_REGISTRY}/${PHP_IMAGE_NAME}:build ; then echo Cache loaded 1>&2 ; fi
   script:
     - cd ${CI_PROJECT_DIR}
     # build the image
-    - buildah build-using-dockerfile --layers -t ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} -f .
-    # save image for the build
-    #- rm -f ${IMAGE_CACHE_FILE}; buildah push ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} docker-archive:${IMAGE_CACHE_FILE}
-    # push image to Target Registry
-    - buildah push --format v2s2 ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} docker://${TARGET_REGISTRY}/${IMAGE_NAME}:build 
+    - buildah build-using-dockerfile
+          -t ${PHP_IMAGE_NAME}:build
+          -f build/php-image/Dockerfile
+          --squash
+          --label cz.knihovny.commit_id=${CI_COMMIT_SHORT_SHA}
+          build/php-image
+    # if on merge request, store the image
+    - if [ "$CI_MERGE_REQUEST_IID" != "" ]; then
+        buildah push --format v2s2 ${PHP_IMAGE_NAME}:build docker://${TARGET_REGISTRY}/${PHP_IMAGE_NAME}:mr-${CI_MERGE_REQUEST_IID};
+      fi
+    # push image to Target Registry (on push)
+    - if [ $CI_PIPELINE_SOURCE == 'push' ]; then
+            buildah push --format v2s2 ${PHP_IMAGE_NAME}:build docker://${TARGET_REGISTRY}/${PHP_IMAGE_NAME}:build;
+            buildah push --format v2s2 ${PHP_IMAGE_NAME}:build docker://${TARGET_REGISTRY}/${PHP_IMAGE_NAME}:branch-${CI_COMMIT_REF_SLUG};
+            buildah push --format v2s2 ${PHP_IMAGE_NAME}:build docker://${TARGET_REGISTRY}/${PHP_IMAGE_NAME}:r-${CI_COMMIT_SHORT_SHA};
+      fi
 
-Deploy container:
+Build app image:
+  stage: build_app
+  image: "${BUILD_JOB_IMAGE}"
+  only:
+    refs:
+      - master
+      - /^devel/
+      - merge_requests
+  artifacts:
+    reports:
+      dotenv:
+        - ~/.artifacts/image_deploy.env
+  before_script:
+    - mkdir -p .artifacts
+    # try to load image from cache registry
+    # try to load image build in some merge-reqeest
+    - HAVE_CACHE_IMAGE=0
+    - echo "Loading PHP base image from mr-${CI_MERGE_REQUEST_IID} image "
+    - |
+      if [ "$CI_MERGE_REQUEST_IID" != "" ]; then
+        if buildah pull --quiet  docker://${CACHE_REGISTRY}/${PHP_IMAGE_NAME}:mr-${CI_MERGE_REQUEST_IID}; then
+             buildah tag ${CACHE_REGISTRY}/${PHP_IMAGE_NAME}:mr-${CI_MERGE_REQUEST_IID} localhost/${PHP_IMAGE_NAME}:build ;
+             HAVE_CACHE_IMAGE=1
+        fi
+      fi
+    - echo "Loading PHP base image from branch-${CI_COMMIT_REF_SLUG} image"
+    - |
+      if [ "$HAVE_CACHE_IMAGE" == 0 ]; then
+        if buildah pull docker://${CACHE_REGISTRY}/${PHP_IMAGE_NAME}:branch-${CI_COMMIT_REF_SLUG}; then
+          buildah tag ${CACHE_REGISTRY}/${PHP_IMAGE_NAME}:branch-${CI_COMMIT_REF_SLUG} localhost/${PHP_IMAGE_NAME}:build ;
+          HAVE_CACHE_IMAGE=1
+        fi
+      fi
+    - echo "Loading PHP base image from default image";
+    - |
+        if [ "$HAVE_CACHE_IMAGE" == 0 ]; then
+            buildah pull --quiet docker://${CACHE_REGISTRY}/${PHP_IMAGE_NAME}:build
+            buildah tag ${CACHE_REGISTRY}/${PHP_IMAGE_NAME}:build localhost/${PHP_IMAGE_NAME}:build ;
+        fi
+
+  script:
+    - cd ${CI_PROJECT_DIR}
+    # change basic image
+    - sed -i "/^FROM/ s@.*@FROM localhost/${PHP_IMAGE_NAME}:build@" build/app/Dockerfile
+    # build the image
+    - buildah build-using-dockerfile
+            --pull-never
+            -t ${IMAGE_NAME}:build
+            -f build/app/Dockerfile
+            --label cz.knihovny.commit_id=${CI_COMMIT_SHORT_SHA}
+            .
+    # push image to Target Registry for future reuse
+    - buildah push --format v2s2 ${IMAGE_NAME}:build docker://${TARGET_REGISTRY}/${IMAGE_NAME}:build
+    # push image to Target Registry (on git push or merge)
+    - echo "Push to repository when required"
+    - |
+       if [ "$CI_PIPELINE_SOURCE" == "push" ] ; then
+            buildah push --format v2s2 ${IMAGE_NAME}:build docker://${TARGET_REGISTRY}/${IMAGE_NAME}:env-${CI_COMMIT_REF_SLUG} ;
+            buildah push --format v2s2 ${IMAGE_NAME}:build docker://${TARGET_REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SORT_SHA} ;
+            buildah push --format v2s2 ${IMAGE_NAME}:build docker://${TARGET_REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID} ;
+       fi
+    - echo "Create deploy.env";
+    - mkdir -p ~/.artifacts; touch ~/.artifacts/image_deploy.env
+    - |
+       if [ "$CI_PIPELINE_SOURCE" == 'push' ]; then
+          echo "APP_IMAGE_NAME=${CACHE_REGISTRY}/${IMAGE_NAME}" >> ~/.artifacts/image_deploy.env;
+          echo "APP_IMAGE_TAG=${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SORT_SHA}" >> ~/.artifacts/image_deploy.env;
+       fi
+
+Deploy devel image:
+  stage: deploy
+  image: "${DEPLOY_JOB_IMAGE}"
   only:
     refs:
       - /^devel/
-  stage: build
+  environment:
+    name: devel
+  variables:
+    APP_IMAGE_NAME: docker.app.knihovny.cz/${IMAGE_NAME}
+    APP_IMAGE_TAG: build
+    GIT_STRATEGY: none # no need to checkout the image
+  script:
+    - mkdir ${HOME}/.ssh; install -m 0600 ${K8S_DEPLOY_KEY} ${HOME}/.ssh/id_rsa
+    - ssh-keyscan gitlab.mzk.cz >> ${HOME}/.ssh/known_hosts
+    - git clone git@gitlab.mzk.cz:knihovny.cz/deploy/registration.git registration
+    - cd registration/devel;
+    - kustomize edit set image registration=${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
+    - git config user.name "CI Robot - for ${GITLAB_USER_NAME}"
+    - git config user.email "<gitlab-cpk@knihovny.cz>"
+    - git add .
+    - |
+        git commit -m "${CI_COMMIT_SHORT_SHA}: Upgrade image version to '${APP_IMAGE_TAG}'"
+    - git push
+
+Deploy master image:
+  stage: deploy
+  only:
+    refs:
+      - master
+      - main
+  environment:
+    name: production
   script:
     - echo OK
